 
export enum FormTypes {
  FORM_FETCH_LOADING = `FORM_FETCH_LOADING`, //开始网络获取

  FORM_CONTENT_SET="FORM_CONTENT_SET", 
  FORM_ACTIVE_ID_SET="FORM_ACTIVE_ID_SET",
  FORM_UPDATE_CONFIG="FORM_UPDATE_CONFIG"

}
